lib/zazaar_web/router.ex
defmodule ZaZaarWeb.Router do
  use ZaZaarWeb, :router

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)

    plug(
      Guardian.Plug.Pipeline,
      module: ZaZaar.Auth.Guardian,
      error_handler: ZaZaar.Auth.ErrorHandler
    )

    plug(Guardian.Plug.VerifySession)
    plug(Guardian.Plug.LoadResource, allow_blank: true)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  pipeline :auth do
    plug(Guardian.Plug.EnsureAuthenticated)
  end

  scope "/", ZaZaarWeb do
    pipe_through(:browser)

    get("/", LiveStreamController, :index)

    get("/about", PageController, :about)
    get("/privacy", PageController, :privacy)
    get("/service", PageController, :service)

    resources("/s", LiveStreamController, only: [:show])

    scope "/auth" do
      get("/:provider", SessionController, :request)
      get("/:provider/callback", SessionController, :callback)
    end

    scope "/m" do
      pipe_through(:auth)

      resources "/", MembershipController, singleton: true, only: [:show] do
        resources("/streaming", StreamingController, only: [:create, :show])
      end

      delete("/logout", SessionController, :delete)

      resources("/messages", MessageController, singleton: true, only: [:show])
    end
  end
end

lib/zazaar_web/views/layout_view.ex
defmodule ZaZaarWeb.LayoutView do
  use ZaZaarWeb, :view

  @doc """
  Generates path for the JavaScript view we want to use
  in this combination of view/template.
  """
  def js_view_path(conn, view_template) do
    [view_name(conn), template_name(view_template)]
    |> Enum.join("/")
  end

  # Takes the resource name of the view module and removes the
  # the ending *_view* string.
  def view_name(conn) do
    conn
    |> view_module
    |> Phoenix.Naming.resource_name()
    |> String.replace("_view", "")
  end

  # Removes the extion from the template and reutrns
  # just the name.
  def template_name(template) when is_binary(template) do
    template
    |> String.split(".")
    |> Enum.at(0)
  end

  def show_flash(conn) do
    conn
    |> get_flash
    |> Enum.map(&flash_html/1)
  end

  def flash_html({level, message}) do
    {:safe,
     """
     <div class='notification is-#{level}'>
       <button class='delete'></button>
       #{message}
     </div>
     """}
  end

  def flash_html(_), do: nil

  def archived_video_url(stream) do
    ot_key = Application.get_env(:zazaar, OpenTok) |> Keyword.get(:key)
    "http://#{Mix.env()}.zazaar.tv.s3.amazonaws.com/#{ot_key}/#{stream.recording_id}/archive.mp4"
  end
end

lib/zazaar_web/templates/layout/_stream_panel.html.eex
<div class="streaming__main is-flex is-flex-column is-justified-between">
  <%= if @stream.archived_at do %>
    <video class="streaming__main__view is-flex is-aligned-start" id="stream-view" src="<%= archived_video_url(@stream) %>" controls autoplay></video>
  <% else %>
    <div class="streaming__main__view is-flex is-aligned-start" id="stream-view">
      <div class="stream__header ">
        <i class="far fa-bullseye"></i>
        <span id="viewer-count">
          <%= @stream.viewer_count %>
        </span>
      </div>
    </div>
  <% end %>

  <div class="streaming__main__info is-flex">
    <a href="#" class="streamer__link is-block">
      <figure class="image is-64x64 streamer__avatar">
        <img class="is-rounded" src="https://bulma.io/images/placeholders/48x48.png">
      </figure>
    </a>
    <div class="streamer__info">
      <h1 class="streamer__title is-size-4">Streaming Title</h1>
      <h2 class="streamer__name has-text-grey-light is-size-5">Streamer's Name</span>
    </div>

      <a class="button is-inverted is-outlined" id="viewer-follow-btn" href="#">
        追蹤
      </a>

    <%= if view_module(@conn) == ZaZaarWeb.LiveStreamView && Map.get(@user, :id) != @stream.streamer_id do %>
      <a class="button is-inverted is-outlined" id="viewer-follow-btn" href="#">
        追蹤
      </a>
    <% end %>
  </div>
</div>

<div class="streaming__chatroom is-flex is-flex-column is-justified-between">
  <span class="streaming__chatroom__title is-block has-text-z-light is-size-6">聊天室</span>
  <div class="streaming__chatroom__log is-flex is-flex-column is-justified-end" id="chat-log">
    <div class="chatroom__log">
      <%= for c <- @stream.comments do %>
        <div class="chatroom__log__message">
          <span><%= c.user_name %></span>
          <%= c.content %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="field streaming__chatroom__input">
    <div class="control">
      <textarea class="textarea" id="user-comment" name="user[comment]" type="text" placeholder="留言..."></textarea>
      <button class="button msgSubmit" id="send-comment">傳送</button>
    </div>
  </div>
</div>

lib/zazaar_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello ZaZaar!</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
    <link rel="stylesheet" href="https://fonts.googleapis.com/earlyaccess/notosanstc.css"/>
  </head>

  <body data-js-view-path="<%= js_view_path(@conn, @view_template) %>" class="<%= view_name(@conn) %> <%= template_name(@view_template) %>">
    <%= render("main_nav.html", conn: @conn) %>
    <%= show_flash(@conn) %>

    <main class="main is-flex">

      <%= if false && current_resource(@conn) do %>
      <aside role="sidebar" class="main-sidebar is-flex has-background-z-dark is-collapsed">
        <%= render("sidebar.html", conn: @conn) %>
      </aside>
      <% end %>

      <div class="main-container">
        <%= render @view_module, @view_template, assigns %>
      </div>

    </main>

    <script src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/zazaar_web/templates/layout/main_nav.html.eex
<nav class="navbar is-flex has-background-zazaar has-shadow" role="navigation" aria-label="main navigation">

  <div class="navbar-brand">
    <a class="navbar-item" href="/">
      <%= svg_image(@conn, "zazaar_logo") %>
    </a>
  </div>

  <div id="main-navbar" class="navbar-menu is-flex is-justified-between has-background-zazaar">

    <%# Search Bar %>
    <%= if false do %>
    <div class="navbar-start search-bar is-flex is-aligned-center">
      <div class="navbar-item">
        <div class="field has-addons">
          <div class="control bar">
            <input class="input z-input" type="text" placeholder="搜尋">
          </div>
          <div class="control z-submit">
            <a class="has-text-white">
              <i class="fal fa-search"></i>
            </a>
          </div>
        </div>
      </div>
    </div>
    <% end %>

    <div class="navbar-end is-flex">
      <%= if current_resource(@conn) do %>
        <a class="navbar-item navbar-icon" href="<%= Routes.message_path(@conn, :show) %>">
          <i class="fas fa-comments"></i>
        </a>

        <%# Notification %>
        <% if false do %>
        <a class="navbar-item navbar-icon">
          <i class="fas fa-bell"></i>
        </a>
        <% end %>

        <%= link(to: Routes.membership_streaming_path(@conn, :create), method: :post, class: "navbar-item button button--zazaar") do %>
          <i class="far fa-bullseye has-text-zazaar"></i>
          開始直播
        <% end %>

        <%= link("登 出", to: "/m/logout", class: "navbar-item button is-outlined", method: :delete)%>

        <%= if false do %>
        <%# User Avatar %>
        <a href="#" class="navbar-item is-avatar">
          <figure class="image is-square">
            <img class="is-rounded" src="https://bulma.io/images/placeholders/48x48.png">
          </figure>
        </a>
        <% end %>

      <% else %>

        <a class="button is-outlined" href="/auth/facebook" >Facebook 登入</a>

      <% end %>
    </div>
  </div>
</nav>

lib/zazaar_web/templates/layout/sidebar.html.eex
<button class="button is-justified-start sidebar-toggle">
  <i class="fal fa-angle-double-right"></i>
</button>

<div class="following is-flex is-flex-wrap">
  <%= for n <- [1, 1, 1, 1, 0, 0, 0, 0, 0, 0] do %> <%# 最多顯示 10 筆 %>
    <a href="#" class="following__user is-flex <%= if n > 0, do: 'online', else: 'offline' %>" >
      <figure class="following__user__avatar image is-32x32">
        <img class="is-rounded" src="https://bulma.io/images/placeholders/128x128.png">
      </figure>
      <span class="following__user__name">
        Username Placeholder
      </span>
    </a>
  <% end %>
  <button class="more-btn"> <%# 10 筆以上預設隱藏，點擊後全部展開 %>
    MORE
    <i class="fal fa-angle-down"></i>
  </button>
</div>

<footer class="z-footer">
  <ul class="guide-links">
    <li><a href="/about" class="item">關於 ZaZaar</a></li>
    <li><a href="/service" class="item">服務條款</a></li>
    <li><a href="/privacy" class="item">隱私權條款</a></li>
  </ul>
  <span class="is-block has-text-zazaar copyright">© 2018 ZaZaar</span>
</footer>

lib/zazaar_web/templates/layout/simple_main.html.eex
<nav class="navbar has-background-bright-orange" role="navigation" aria-label="main navigation">
  <div class="container">
    <div class="navbar-brand">
      <a class="navbar-item" href="/" id="logo-item">
        <img src="<%= static_path(@conn, "/images/zazaar_logo_white.svg") %>" alt="logo" id="logo"/>
      </a>

      <%= if current_resource(@conn) do %>
        <div class="navbar-item">
          <a href="<%= membership_streaming_path(@conn, :show) %>" class="button is-danger is-rounded is-red">
            <i class="far fa-bullseye"></i>
            開始直播
          </a>
        </div>
        <div class="navbar-item">
          <%= link("登 出", to: "/m/logout", class: "button is-link is-inverted is-outlined", method: :delete)%>
        </div>
      <% else %>
        <div class="navbar-item">
          <a href="/auth/facebook" class="button is-link is-inverted is-outlined"> FB 登入</a>
        </div>
      <% end %>
    </div>
  </div>
  </div>
</nav>