lib/zazaar_web/router.ex
defmodule ZaZaarWeb.Router do
  use ZaZaarWeb, :router

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)

    plug(
      Guardian.Plug.Pipeline,
      module: ZaZaar.Auth.Guardian,
      error_handler: ZaZaar.Auth.ErrorHandler
    )

    plug(Guardian.Plug.VerifySession)
    plug(Guardian.Plug.LoadResource, allow_blank: true)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  pipeline :auth do
    plug(Guardian.Plug.EnsureAuthenticated)
  end

  scope "/", ZaZaarWeb do
    pipe_through(:browser)

    get("/", LiveStreamController, :index)

    get("/about", PageController, :about)
    get("/privacy", PageController, :privacy)
    get("/service", PageController, :service)

    resources("/s", LiveStreamController, only: [:show])

    scope "/auth" do
      get("/:provider", SessionController, :request)
      get("/:provider/callback", SessionController, :callback)
    end

    scope "/m" do
      pipe_through(:auth)

      resources "/", MembershipController, singleton: true, only: [:show] do
        resources("/streaming", StreamingController, only: [:create, :show])
      end

      delete("/logout", SessionController, :delete)

      resources("/messages", MessageController, singleton: true, only: [:show])
    end
  end
end

lib/zazaar_web/controllers/live_stream_controller.ex
defmodule ZaZaarWeb.LiveStreamController do
  use ZaZaarWeb, :controller

  action_fallback(FallbackController)

  alias ZaZaarWeb.StreamPresence, as: Presence

  def index(conn, _params) do
    with streams0 <- Streaming.get_streams(order_by: [desc: :archived_at, desc: :inserted_at]),
         streamer_ids <- Enum.map(streams0, & &1.streamer_id),
         users <- Account.get_users(streamer_ids),
         streams1 <- append_info(streams0, users) do
      render(conn, "index.html", streams: streams1)
    end
  end

  def show(conn, %{"id" => stream_id}) do
    with stream0 <- Streaming.get_stream(stream_id),
         comments <- include_user_names(stream0.comments) do
      stream1 =
        stream0
        |> Map.put(:comments, comments)
        |> Map.put_new(:viewer_count, get_viewer_count(stream0))

      user = current_resource(conn) || %User{}
      render(conn, "show.html", stream: stream1, user: user)
    end
  end

  defp append_info(streams, users) do
    Enum.map(streams, fn stream ->
      user = Enum.find(users, &(&1.id == stream.streamer_id))

      stream
      |> Map.put_new(:streamer, user)
      |> Map.put_new(:viewer_count, get_viewer_count(stream))
    end)
  end

  defp get_viewer_count(stream) do
    Presence.list("stream:" <> stream.id) |> Enum.count()
  end

  defp include_user_names(comments) do
    users =
      comments
      |> Enum.map(& &1.user_id)
      |> Enum.uniq()
      |> Account.get_users()

    Enum.map(comments, fn c ->
      name =
        users
        |> Enum.find(&(&1.id == c.user_id))
        |> Map.get(:name)

      Map.put(c, :user_name, name)
    end)
  end
end

lib/zazaar_web/views/live_stream_view.ex
defmodule ZaZaarWeb.LiveStreamView do
  use ZaZaarWeb, :view

  def cal_time_diff(dt0, dt1) do
    seconds_diff =
      NaiveDateTime.diff(dt0, dt1)
      |> abs

    seconds = rem(seconds_diff, 60)
    minutes = div(seconds_diff, 60)
    hours = div(seconds_diff, 3600)

    [hours, minutes, seconds]
    |> Enum.join(":")
  end
end

lib/zazaar_web/templates/live_stream/_popularStream.html.eex
<%= if false do %>
  <%= link to: Routes.live_stream_path(@conn, :show, @channel.streamer_id) do %>
    <%#display default image if snapshot does not exist%>
    <%= if @channel.video_snapshot do %>
      <img src="data:image/png;base64, <%= @channel.video_snapshot %>" class="ui rounded image" />
    <% else %>
      <img src="http://via.placeholder.com/150x120" class="ui rounded image" />
    <% end %>
  <% end %>
<% end %>

<div class="popular-stream">

  <div class="featured-stream">

    <div class="video-player" style="background-image:url(http://via.placeholder.com/840x420)">

      <div class="video-player__header is-inline-block">
        <i class="far fa-bullseye"></i>
        2048 <%# 正在觀看人數 %>
      </div>

      <div class="video-player__control-bar is-gradient is-flex"> <%# Video Control Bar %>
        <div class="video-player__play-control">
          <i class="fas fa-stop"></i>
          <i class="fas fa-volume-down"></i>
          <%# 這邊還需要一個音量控制器 %>
        </div>
        <div class="video-player__action-control">
          <i class="fas fa-share-alt"></i>
          <i class="fas fa-flag"></i>
          <i class="fas fa-expand-alt"></i>
        </div>
      </div>
    </div>

    <div class="featured-stream__intro is-flex">
      <figure class="featured-stream__avatar image">
        <img class="is-rounded" src="https://bulma.io/images/placeholders/128x128.png">
      </figure>
      <div class="featured-stream__info">
        <h3 class="featured-stream__title">Video Title<h3>
        <span class="featured-stream__name">Streamer's Name</span>
      </div>
    </div>

  </div>

  <div class="top-streams is-flex">

    <%= for _ <- [1, 1, 1] do %> <%# 最多顯示 10 筆 %>

      <div class="top-streams__block">

        <div class="video-player" style="background-image:url(http://via.placeholder.com/240x120)">
          <div class="video-player__header is-inline-block">
            <i class="far fa-bullseye"></i>
            1048 <%# 正在觀看人數 %>
          </div>
        </div>

        <h3 class="top-streams__title">Video Title<h3>

      </div>
    <% end%>
  </div>
</div>

lib/zazaar_web/templates/live_stream/_stream.html.eex
<div class="column is-half-tablet is-one-third-desktop">
  <%= link to: Routes.live_stream_path(@conn, :show, @stream.id) do %>
    <%= if @stream.video_snapshot do %>
      <div class="stream" style="background-image:url(data:image/png;base64,<%= @stream.video_snapshot %>)">
    <% else %>
      <div class="stream" style="background-image:url(https://dummyimage.com/600x400/ddd/ddd.png)">
    <% end %>
      <div class="stream__header">
        <%= if @stream.archived_at == nil do %>
          <i class="far fa-bullseye"></i>
          <%= @stream.viewer_count %>
        <% else %>
          <i class="fas fa-play"></i>
          <%= cal_time_diff(@stream.archived_at, @stream.inserted_at) %>
        <% end %>
      </div>
      <div class="is-flex is-32x32 has-z-gradient stream__footer">
        <figure class="image stream__avatar">
          <img class="is-rounded" src="http://via.placeholder.com/32x32.png"/>
        </figure>
        <h3 class="stream__title"><%= @stream.streamer.name %> 的直播<h3>
      </div>
    </div>
  <% end %>
</div>

lib/zazaar_web/templates/live_stream/index.html.eex
<section class="section live-stream">
  <div class="container">
    <% if false do %>
      <h2 class="title has-text-weight-semibold has-text-zazaar">熱門賣場</h2>
      <%= render("_popularStream.html", conn: @conn) %>
    <% end %>

    <header>
      <h2 class="title has-text-weight-semibold has-text-zazaar has-border-bottom-zazaar">推薦賣場</h2>
    </header>

    <div class="live-stream__list">
      <div class="columns is-flex-wrap">
        <%= render_many @streams, __MODULE__, "_stream.html", as: :stream, conn: @conn %>
      </div>
    </div>
  </div>
</section>

lib/zazaar_web/templates/live_stream/show.html.eex
<div class="streaming is-flex">
  <%= render(ZaZaarWeb.LayoutView, "_stream_panel.html", conn: @conn, stream: @stream, user: @user) %>
</div>

<script charset="utf-8">

  window.streamConfig =
    {
      user_id: '<%= @user.id %>',
      stream_id: '<%= @stream.id %>',
      streamer_id: '<%= @stream.streamer_id %>',
      jwt: '<%= current_token(@conn) %>'
    }

</script>